/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.mysql.jdbc.Statement;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author renzo
 */
public class Interfaz extends javax.swing.JFrame {
   
    ConexionBD con = new ConexionBD();
    Connection cn = con.conexion();
    
   
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void validarAcceso(){
        
        int resultado=0;
        
        try{
            String usuario=txtusuario.getText();
            String contraseña=String.valueOf(txtcontraseña.getPassword());
            
            String sql="SELECT * FROM usuarios where nombre='"+nombre"' and contraseña='"+contraseña"'";
            
            Statement cn=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            
            if(rs.next()){
                
                resultado=1;
                
                if(resultado==1){
                    
                    MenuPrincipal form=new MenuPrincipal();
                    form.setVisible(true);
                    this.dispose();
                }else{
                    
                    JOptionPane.showMessageDialog(null,"Datos invalidos");
                }
        
    } catch (Exception e){
            
                    JOptionPane.showMessageDialog(null,"Datos invalidos" + e.getmessage());
        
    } 
        }
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/farmasaludicono.png"));
       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSALIR = new javax.swing.JButton();
        jlbUSUARIO = new javax.swing.JLabel();
        jlbCONTRASEÑA = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        jButtonsesion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSALIR.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jButtonSALIR.setText("Salir");
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        jlbUSUARIO.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jlbUSUARIO.setText("Usuario");
        getContentPane().add(jlbUSUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 110, 30));

        jlbCONTRASEÑA.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jlbCONTRASEÑA.setText("Contraseña");
        getContentPane().add(jlbCONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        txtusuario.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 160, 30));

        txtcontraseña.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        txtcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 160, 30));

        jButtonsesion.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButtonsesion.setText("Iniciar Sesion");
        jButtonsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 170, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/farmasaludicono.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 810, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo02.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 822, 562));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSALIRActionPerformed

    private void jButtonsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsesionActionPerformed
        AgregarUsuario();        
    }
       
    }//GEN-LAST:event_jButtonsesionActionPerformed

     
    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaActionPerformed

   
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JButton jButtonsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlbCONTRASEÑA;
    private javax.swing.JLabel jlbUSUARIO;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
