/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.print.*;
import java.text.*;
/**
 *
 * @author renzo
 */

public class RegistrarVenta extends javax.swing.JFrame implements Printable{

    /**
     * Creates new form RegistrarVenta
     */
    public RegistrarVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLFactura = new javax.swing.JLabel();
        jLCant = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLproducto = new javax.swing.JLabel();
        jLPrecio = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLPrecioTotal = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLSubtotal = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        JLIVA = new javax.swing.JLabel();
        JLTotal = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFactura.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLFactura.setForeground(new java.awt.Color(255, 255, 0));
        jLFactura.setText("Factura FarmaSalud");
        getContentPane().add(jLFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 210, 60));

        jLCant.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLCant.setForeground(new java.awt.Color(255, 255, 0));
        jLCant.setText("Cantidad:");
        getContentPane().add(jLCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 100, 40));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 130, 30));

        jButton5.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 80, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 80, 30));

        jLproducto.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLproducto.setForeground(new java.awt.Color(255, 255, 0));
        jLproducto.setText("Producto:");
        getContentPane().add(jLproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 80, 40));

        jLPrecio.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLPrecio.setForeground(new java.awt.Color(255, 255, 0));
        jLPrecio.setText("Precio:");
        getContentPane().add(jLPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 80, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 80, 30));

        jLPrecioTotal.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLPrecioTotal.setForeground(new java.awt.Color(255, 255, 0));
        jLPrecioTotal.setText("Precio total:");
        getContentPane().add(jLPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 110, 30));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 120, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 80, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 130, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 80, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 120, 30));

        jLSubtotal.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLSubtotal.setForeground(new java.awt.Color(255, 255, 0));
        jLSubtotal.setText("Subtotal:");
        getContentPane().add(jLSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 80, 30));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 120, 30));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 120, 30));

        JLIVA.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        JLIVA.setForeground(new java.awt.Color(255, 255, 0));
        JLIVA.setText("IVA:");
        getContentPane().add(JLIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 70, 30));

        JLTotal.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        JLTotal.setForeground(new java.awt.Color(255, 255, 0));
        JLTotal.setText("Total:");
        getContentPane().add(JLTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 80, 30));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 120, 30));

        jButton1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 120, 40));

        jButton2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 120, 40));

        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 994, 562));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    this.setVisible(false); 
    new MenuPrincipal().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
      
        
        

    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        double pro1,pro2,vup1,vup2,vtp1,vtp2,subtotal,iva,preciototal;
        pro1=Double.parseDouble(jTextField1.getText());
        pro2=Double.parseDouble(jTextField2.getText());
        vup1=Double.parseDouble(jTextField5.getText());
        vup2=Double.parseDouble(jTextField6.getText());
       
        vtp1=pro1*vup1;
        vtp2=pro2*vup2; 
        String valt1=vtp1 + "";
        String valt2=vtp2 + "";
        jTextField7.setText(valt1);
        jTextField8.setText(valt2);
        subtotal=vtp1+vtp2;
        String sT=subtotal + "";
        jTextField9.setText(sT);
        iva=subtotal*0.19;
        String IVA=iva + "";
        jTextField10.setText (IVA);
        preciototal=subtotal+iva;
        String vp=preciototal + "";
        jTextField11.setText(vp);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        try
       {
           PrinterJob imprticket = PrinterJob.getPrinterJob();
           imprticket .setPrintable(this);
           boolean impr = imprticket .printDialog();
            
           if(impr)
           {
               imprticket.print();
           }
       }
       catch(PrinterException pex)
       {
           System.out.println("Error\n" + pex);
       }
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLIVA;
    private javax.swing.JLabel JLTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLCant;
    private javax.swing.JLabel jLFactura;
    private javax.swing.JLabel jLPrecio;
    private javax.swing.JLabel jLPrecioTotal;
    private javax.swing.JLabel jLSubtotal;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JLabel jLproducto;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int page) throws PrinterException
    {
        if(page > 0)//Esto porque solo es una página que se imprime
        {
            return NO_SUCH_PAGE;
        }
        Graphics2D bot = (Graphics2D) graf;
        bot.translate(pagfor.getImageableX() + 30, pagfor.getImageableY()+ 30);
        bot.scale(1.0, 1.0);//Tamaño normal, si quisieramos el doble seria 2.0, 2.0
        printAll(graf);//Imprime todo lo que hay en el JPanel factura
        return PAGE_EXISTS;
    }
    
        
    
}
